### PR TITLE
GPS9 Tag Support

### PR DESCRIPTION
**Pull request by hannasm**
The latest GoPro 11 cameras do not emit GPS5 KLVs anymore. This code pulls data from the new GPS9 KLV into the existing data structures and should coexist perfectly well with the older GPS5 klvs

### CODE REVIEW

**Review by vadimaus — APPROVED** [review]
Thanks @hannasm for your contribution! This was a long overdue.

**Comment by vadimaus** [comment]
@hannasm Tested with a GoPro 11 video and it actually have both of them, GPS5 and GPS9.
So the resulting file has combined values.

**Comment by hannasm** [comment]
Hmmm, you are right, i am reviewing my sample videos again and they
definitely have GPS5 data. At the time i worked on this i could have sworn
the GPS5 data was not in there...

Would it make sense to just discard the GPS5 once it's known GPS9 is
present?

The clock on the GPS5 data seems to be about 1 second delayed from the GPS9
data but otherwise the data seems nearly identical on the videos i tested
today.

**Comment by vadimaus** [comment]
@hannasm Need to think how to discard the GPS5.

**Pull request merged**
